interface KeyVar {
  key?: string
}

interface CSSStyleVariableDeclaration {
  alignContent?:  string | KeyVar;
  alignItems?:  string | KeyVar;
  alignSelf?:  string | KeyVar;
  alignmentBaseline?:  string | KeyVar;
  animation?:  string | KeyVar;
  animationDelay?:  string | KeyVar;
  animationDirection?:  string | KeyVar;
  animationDuration?:  string | KeyVar;
  animationFillMode?:  string | KeyVar;
  animationIterationCount?:  string | KeyVar;
  animationName?:  string | KeyVar;
  animationPlayState?:  string | KeyVar;
  animationTimingFunction?:  string | KeyVar;
  backfaceVisibility?:  string | KeyVar;
  background?:  string | KeyVar;
  backgroundAttachment?:  string | KeyVar;
  backgroundClip?:  string | KeyVar;
  backgroundColor?:  string | KeyVar;
  backgroundImage?:  string | KeyVar;
  backgroundOrigin?:  string | KeyVar;
  backgroundPosition?:  string | KeyVar;
  backgroundPositionX?:  string | KeyVar;
  backgroundPositionY?:  string | KeyVar;
  backgroundRepeat?:  string | KeyVar;
  backgroundSize?:  string | KeyVar;
  baselineShift?:  string | KeyVar;
  border?:  string | KeyVar;
  borderBottom?:  string | KeyVar;
  borderBottomColor?:  string | KeyVar;
  borderBottomLeftRadius?:  string | KeyVar;
  borderBottomRightRadius?:  string | KeyVar;
  borderBottomStyle?:  string | KeyVar;
  borderBottomWidth?:  string | KeyVar;
  borderCollapse?:  string | KeyVar;
  borderColor?:  string | KeyVar;
  borderImage?:  string | KeyVar;
  borderImageOutset?:  string | KeyVar;
  borderImageRepeat?:  string | KeyVar;
  borderImageSlice?:  string | KeyVar;
  borderImageSource?:  string | KeyVar;
  borderImageWidth?:  string | KeyVar;
  borderLeft?:  string | KeyVar;
  borderLeftColor?:  string | KeyVar;
  borderLeftStyle?:  string | KeyVar;
  borderLeftWidth?:  string | KeyVar;
  borderRadius?:  string | KeyVar;
  borderRight?:  string | KeyVar;
  borderRightColor?:  string | KeyVar;
  borderRightStyle?:  string | KeyVar;
  borderRightWidth?:  string | KeyVar;
  borderSpacing?:  string | KeyVar;
  borderStyle?:  string | KeyVar;
  borderTop?:  string | KeyVar;
  borderTopColor?:  string | KeyVar;
  borderTopLeftRadius?:  string | KeyVar;
  borderTopRightRadius?:  string | KeyVar;
  borderTopStyle?:  string | KeyVar;
  borderTopWidth?:  string | KeyVar;
  borderWidth?:  string | KeyVar;
  bottom?:  string | KeyVar;
  boxShadow?:  string | KeyVar;
  boxSizing?:  string | KeyVar;
  breakAfter?:  string | KeyVar;
  breakBefore?:  string | KeyVar;
  breakInside?:  string | KeyVar;
  captionSide?:  string | KeyVar;
  clear?:  string | KeyVar;
  clip?:  string | KeyVar;
  clipPath?:  string | KeyVar;
  clipRule?:  string | KeyVar;
  color?:  string | KeyVar;
  colorInterpolationFilters?:  string | KeyVar;
  columnCount?: any;
  columnFill?:  string | KeyVar;
  columnGap?: any;
  columnRule?:  string | KeyVar;
  columnRuleColor?: any;
  columnRuleStyle?:  string | KeyVar;
  columnRuleWidth?: any;
  columnSpan?:  string | KeyVar;
  columnWidth?: any;
  columns?:  string | KeyVar;
  content?:  string | KeyVar;
  counterIncrement?:  string | KeyVar;
  counterReset?:  string | KeyVar;
  cssFloat?:  string | KeyVar;
  cssText?: string;
  cursor?:  string | KeyVar;
  direction?:  string | KeyVar;
  display?:  string | KeyVar;
  dominantBaseline?:  string | KeyVar;
  emptyCells?:  string | KeyVar;
  enableBackground?:  string | KeyVar;
  fill?:  string | KeyVar;
  fillOpacity?:  string | KeyVar;
  fillRule?:  string | KeyVar;
  filter?:  string | KeyVar;
  flex?:  string | KeyVar;
  flexBasis?:  string | KeyVar;
  flexDirection?:  string | KeyVar;
  flexFlow?:  string | KeyVar;
  flexGrow?:  string | KeyVar;
  flexShrink?:  string | KeyVar;
  flexWrap?:  string | KeyVar;
  floodColor?:  string | KeyVar;
  floodOpacity?:  string | KeyVar;
  font?:  string | KeyVar;
  fontFamily?:  string | KeyVar;
  fontFeatureSettings?:  string | KeyVar;
  fontSize?:  string | KeyVar;
  fontSizeAdjust?:  string | KeyVar;
  fontStretch?:  string | KeyVar;
  fontStyle?:  string | KeyVar;
  fontVariant?:  string | KeyVar;
  fontWeight?:  string | KeyVar;
  glyphOrientationHorizontal?:  string | KeyVar;
  glyphOrientationVertical?:  string | KeyVar;
  height?:  string | KeyVar;
  imeMode?:  string | KeyVar;
  justifyContent?:  string | KeyVar;
  kerning?:  string | KeyVar;
  layoutGrid?:  string | KeyVar;
  layoutGridChar?:  string | KeyVar;
  layoutGridLine?:  string | KeyVar;
  layoutGridMode?:  string | KeyVar;
  layoutGridType?:  string | KeyVar;
  left?:  string | KeyVar;
  readonly length?: number;
  letterSpacing?:  string | KeyVar;
  lightingColor?:  string | KeyVar;
  lineBreak?:  string | KeyVar;
  lineHeight?:  string | KeyVar;
  listStyle?:  string | KeyVar;
  listStyleImage?:  string | KeyVar;
  listStylePosition?:  string | KeyVar;
  listStyleType?:  string | KeyVar;
  margin?:  string | KeyVar;
  marginBottom?:  string | KeyVar;
  marginLeft?:  string | KeyVar;
  marginRight?:  string | KeyVar;
  marginTop?:  string | KeyVar;
  marker?:  string | KeyVar;
  markerEnd?:  string | KeyVar;
  markerMid?:  string | KeyVar;
  markerStart?:  string | KeyVar;
  mask?:  string | KeyVar;
  maxHeight?:  string | KeyVar;
  maxWidth?:  string | KeyVar;
  minHeight?:  string | KeyVar;
  minWidth?:  string | KeyVar;
  msContentZoomChaining?:  string | KeyVar;
  msContentZoomLimit?:  string | KeyVar;
  msContentZoomLimitMax?: any;
  msContentZoomLimitMin?: any;
  msContentZoomSnap?:  string | KeyVar;
  msContentZoomSnapPoints?:  string | KeyVar;
  msContentZoomSnapType?:  string | KeyVar;
  msContentZooming?:  string | KeyVar;
  msFlowFrom?:  string | KeyVar;
  msFlowInto?:  string | KeyVar;
  msFontFeatureSettings?:  string | KeyVar;
  msGridColumn?: any;
  msGridColumnAlign?:  string | KeyVar;
  msGridColumnSpan?: any;
  msGridColumns?:  string | KeyVar;
  msGridRow?: any;
  msGridRowAlign?:  string | KeyVar;
  msGridRowSpan?: any;
  msGridRows?:  string | KeyVar;
  msHighContrastAdjust?:  string | KeyVar;
  msHyphenateLimitChars?:  string | KeyVar;
  msHyphenateLimitLines?: any;
  msHyphenateLimitZone?: any;
  msHyphens?:  string | KeyVar;
  msImeAlign?:  string | KeyVar;
  msOverflowStyle?:  string | KeyVar;
  msScrollChaining?:  string | KeyVar;
  msScrollLimit?:  string | KeyVar;
  msScrollLimitXMax?: any;
  msScrollLimitXMin?: any;
  msScrollLimitYMax?: any;
  msScrollLimitYMin?: any;
  msScrollRails?:  string | KeyVar;
  msScrollSnapPointsX?:  string | KeyVar;
  msScrollSnapPointsY?:  string | KeyVar;
  msScrollSnapType?:  string | KeyVar;
  msScrollSnapX?:  string | KeyVar;
  msScrollSnapY?:  string | KeyVar;
  msScrollTranslation?:  string | KeyVar;
  msTextCombineHorizontal?:  string | KeyVar;
  msTextSizeAdjust?: any;
  msTouchAction?:  string | KeyVar;
  msTouchSelect?:  string | KeyVar;
  msUserSelect?:  string | KeyVar;
  msWrapFlow?: string;
  msWrapMargin?: any;
  msWrapThrough?: string;
  opacity?:  string | KeyVar;
  order?:  string | KeyVar;
  orphans?:  string | KeyVar;
  outline?:  string | KeyVar;
  outlineColor?:  string | KeyVar;
  outlineOffset?:  string | KeyVar;
  outlineStyle?:  string | KeyVar;
  outlineWidth?:  string | KeyVar;
  overflow?:  string | KeyVar;
  overflowX?:  string | KeyVar;
  overflowY?:  string | KeyVar;
  padding?:  string | KeyVar;
  paddingBottom?:  string | KeyVar;
  paddingLeft?:  string | KeyVar;
  paddingRight?:  string | KeyVar;
  paddingTop?:  string | KeyVar;
  pageBreakAfter?:  string | KeyVar;
  pageBreakBefore?:  string | KeyVar;
  pageBreakInside?:  string | KeyVar;
  readonly parentRule?: CSSRule;
  perspective?:  string | KeyVar;
  perspectiveOrigin?:  string | KeyVar;
  pointerEvents?:  string | KeyVar;
  position?:  string | KeyVar;
  quotes?:  string | KeyVar;
  right?:  string | KeyVar;
  rotate?:  string | KeyVar;
  rubyAlign?:  string | KeyVar;
  rubyOverhang?:  string | KeyVar;
  rubyPosition?:  string | KeyVar;
  scale?:  string | KeyVar;
  stopColor?:  string | KeyVar;
  stopOpacity?:  string | KeyVar;
  stroke?:  string | KeyVar;
  strokeDasharray?:  string | KeyVar;
  strokeDashoffset?:  string | KeyVar;
  strokeLinecap?:  string | KeyVar;
  strokeLinejoin?:  string | KeyVar;
  strokeMiterlimit?:  string | KeyVar;
  strokeOpacity?:  string | KeyVar;
  strokeWidth?:  string | KeyVar;
  tableLayout?:  string | KeyVar;
  textAlign?:  string | KeyVar;
  textAlignLast?:  string | KeyVar;
  textAnchor?:  string | KeyVar;
  textDecoration?:  string | KeyVar;
  textIndent?:  string | KeyVar;
  textJustify?:  string | KeyVar;
  textKashida?:  string | KeyVar;
  textKashidaSpace?:  string | KeyVar;
  textOverflow?:  string | KeyVar;
  textShadow?:  string | KeyVar;
  textTransform?:  string | KeyVar;
  textUnderlinePosition?:  string | KeyVar;
  top?:  string | KeyVar;
  touchAction?:  string | KeyVar;
  transform?:  string | KeyVar;
  transformOrigin?:  string | KeyVar;
  transformStyle?:  string | KeyVar;
  transition?:  string | KeyVar;
  transitionDelay?:  string | KeyVar;
  transitionDuration?:  string | KeyVar;
  transitionProperty?:  string | KeyVar;
  transitionTimingFunction?:  string | KeyVar;
  translate?:  string | KeyVar;
  unicodeBidi?:  string | KeyVar;
  verticalAlign?:  string | KeyVar;
  visibility?:  string | KeyVar;
  webkitAlignContent?:  string | KeyVar;
  webkitAlignItems?:  string | KeyVar;
  webkitAlignSelf?:  string | KeyVar;
  webkitAnimation?:  string | KeyVar;
  webkitAnimationDelay?:  string | KeyVar;
  webkitAnimationDirection?:  string | KeyVar;
  webkitAnimationDuration?:  string | KeyVar;
  webkitAnimationFillMode?:  string | KeyVar;
  webkitAnimationIterationCount?:  string | KeyVar;
  webkitAnimationName?:  string | KeyVar;
  webkitAnimationPlayState?:  string | KeyVar;
  webkitAnimationTimingFunction?:  string | KeyVar;
  webkitAppearance?:  string | KeyVar;
  webkitBackfaceVisibility?:  string | KeyVar;
  webkitBackgroundClip?:  string | KeyVar;
  webkitBackgroundOrigin?:  string | KeyVar;
  webkitBackgroundSize?:  string | KeyVar;
  webkitBorderBottomLeftRadius?:  string | KeyVar;
  webkitBorderBottomRightRadius?:  string | KeyVar;
  webkitBorderImage?:  string | KeyVar;
  webkitBorderRadius?:  string | KeyVar;
  webkitBorderTopLeftRadius?:  string | KeyVar;
  webkitBorderTopRightRadius?:  string | KeyVar;
  webkitBoxAlign?:  string | KeyVar;
  webkitBoxDirection?:  string | KeyVar;
  webkitBoxFlex?:  string | KeyVar;
  webkitBoxOrdinalGroup?:  string | KeyVar;
  webkitBoxOrient?:  string | KeyVar;
  webkitBoxPack?:  string | KeyVar;
  webkitBoxSizing?:  string | KeyVar;
  webkitColumnBreakAfter?:  string | KeyVar;
  webkitColumnBreakBefore?:  string | KeyVar;
  webkitColumnBreakInside?:  string | KeyVar;
  webkitColumnCount?: any;
  webkitColumnGap?: any;
  webkitColumnRule?:  string | KeyVar;
  webkitColumnRuleColor?: any;
  webkitColumnRuleStyle?:  string | KeyVar;
  webkitColumnRuleWidth?: any;
  webkitColumnSpan?:  string | KeyVar;
  webkitColumnWidth?: any;
  webkitColumns?:  string | KeyVar;
  webkitFilter?:  string | KeyVar;
  webkitFlex?:  string | KeyVar;
  webkitFlexBasis?:  string | KeyVar;
  webkitFlexDirection?:  string | KeyVar;
  webkitFlexFlow?:  string | KeyVar;
  webkitFlexGrow?:  string | KeyVar;
  webkitFlexShrink?:  string | KeyVar;
  webkitFlexWrap?:  string | KeyVar;
  webkitJustifyContent?:  string | KeyVar;
  webkitOrder?:  string | KeyVar;
  webkitPerspective?:  string | KeyVar;
  webkitPerspectiveOrigin?:  string | KeyVar;
  webkitTapHighlightColor?:  string | KeyVar;
  webkitTextFillColor?:  string | KeyVar;
  webkitTextSizeAdjust?: any;
  webkitTextStroke?:  string | KeyVar;
  webkitTextStrokeColor?:  string | KeyVar;
  webkitTextStrokeWidth?:  string | KeyVar;
  webkitTransform?:  string | KeyVar;
  webkitTransformOrigin?:  string | KeyVar;
  webkitTransformStyle?:  string | KeyVar;
  webkitTransition?:  string | KeyVar;
  webkitTransitionDelay?:  string | KeyVar;
  webkitTransitionDuration?:  string | KeyVar;
  webkitTransitionProperty?:  string | KeyVar;
  webkitTransitionTimingFunction?:  string | KeyVar;
  webkitUserModify?:  string | KeyVar;
  webkitUserSelect?:  string | KeyVar;
  webkitWritingMode?:  string | KeyVar;
  whiteSpace?:  string | KeyVar;
  widows?:  string | KeyVar;
  width?:  string | KeyVar;
  wordBreak?:  string | KeyVar;
  wordSpacing?:  string | KeyVar;
  wordWrap?:  string | KeyVar;
  writingMode?:  string | KeyVar;
  zIndex?:  string | KeyVar;
  zoom?:  string | KeyVar;
  resize?:  string | KeyVar;
  userSelect?:  string | KeyVar;
}

export default CSSStyleVariableDeclaration